In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1271, 2078, 7248, 1565],
 [1271, 2078, 7248, 2179],
 [1271, 4923, 7248, 4433],
 [616, 1313, 2765, 705, 8606],
 [616, 1313, 2765, 705, 512],
 [4852, 1271, 4223, 7248, 5423],
 [5181, 7404, 4001, 705]]

In [ ]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1271 2078 7248 1565]
 [   0    0    0    0 1271 2078 7248 2179]
 [   0    0    0    0 1271 4923 7248 4433]
 [   0    0    0  616 1313 2765  705 8606]
 [   0    0    0  616 1313 2765  705  512]
 [   0    0    0 4852 1271 4223 7248 5423]
 [   0    0    0    0 5181 7404 4001  705]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 529ms/step


array([[[-0.02714967, -0.02566795,  0.01764901, -0.02798182,
          0.01567462, -0.02151524, -0.02333055,  0.03453084,
          0.01392293,  0.00760814],
        [-0.02714967, -0.02566795,  0.01764901, -0.02798182,
          0.01567462, -0.02151524, -0.02333055,  0.03453084,
          0.01392293,  0.00760814],
        [-0.02714967, -0.02566795,  0.01764901, -0.02798182,
          0.01567462, -0.02151524, -0.02333055,  0.03453084,
          0.01392293,  0.00760814],
        [-0.02714967, -0.02566795,  0.01764901, -0.02798182,
          0.01567462, -0.02151524, -0.02333055,  0.03453084,
          0.01392293,  0.00760814],
        [-0.00148684,  0.03123394, -0.00324235,  0.03057815,
          0.04204675,  0.04175428, -0.04662253,  0.01705971,
         -0.04983613,  0.04419405],
        [-0.0022798 , -0.04542909,  0.02575228, -0.00093316,
          0.01053095, -0.01107915, -0.00017719,  0.0160774 ,
         -0.02425063,  0.00657439],
        [ 0.01695821,  0.02716157,  0.04606719, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 1271, 2078, 7248, 1565])

In [17]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 63ms/step


array([[-0.02714967, -0.02566795,  0.01764901, -0.02798182,  0.01567462,
        -0.02151524, -0.02333055,  0.03453084,  0.01392293,  0.00760814],
       [-0.02714967, -0.02566795,  0.01764901, -0.02798182,  0.01567462,
        -0.02151524, -0.02333055,  0.03453084,  0.01392293,  0.00760814],
       [-0.02714967, -0.02566795,  0.01764901, -0.02798182,  0.01567462,
        -0.02151524, -0.02333055,  0.03453084,  0.01392293,  0.00760814],
       [-0.02714967, -0.02566795,  0.01764901, -0.02798182,  0.01567462,
        -0.02151524, -0.02333055,  0.03453084,  0.01392293,  0.00760814],
       [-0.00148684,  0.03123394, -0.00324235,  0.03057815,  0.04204675,
         0.04175428, -0.04662253,  0.01705971, -0.04983613,  0.04419405],
       [-0.0022798 , -0.04542909,  0.02575228, -0.00093316,  0.01053095,
        -0.01107915, -0.00017719,  0.0160774 , -0.02425063,  0.00657439],
       [ 0.01695821,  0.02716157,  0.04606719, -0.01190249,  0.00940201,
        -0.04014777, -0.00921414, -0.02200936